In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('iris.data',header=None)

In [3]:
df.columns =['SLength','SWidth','PLength','Pwidth','class']

In [4]:
df.replace('Iris-setosa',0,inplace=True)
df.replace('Iris-versicolor',1,inplace=True)
df.replace('Iris-virginica',2,inplace=True)
df['class'].astype(int)

C:\Users\jerri\AppData\Local\Temp\ipykernel_2408\1468863356.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace('Iris-virginica',2,inplace=True)


0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: class, Length: 150, dtype: int32

In [5]:
X= df.drop(columns=['class'])
y =df['class']

In [6]:
df.dtypes

SLength    float64
SWidth     float64
PLength    float64
Pwidth     float64
class        int64
dtype: object

In [7]:
from sklearn.model_selection import train_test_split
X_train_val,X_test,y_train_val,y_test =train_test_split(
    X,y,test_size=0.15,random_state=42
)

KNN algorithm from scratch

In [8]:
#stratifies splitting
from sklearn.model_selection import StratifiedShuffleSplit
knn_split = StratifiedShuffleSplit(n_splits=1,test_size=0.05,random_state=42)


In [9]:
X=df.drop(columns='class')
y=df['class']
for train_idx,test_idx in knn_split.split(X,y):
    X_train,X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train,y_test = y.iloc[train_idx], y.iloc[test_idx]

In [ ]:
# once we compute euclidean distance ,we need class labels after sorting,so that we can understand which is which.so we concat
combined_df =pd.concat([X_train,y_train],axis=1)
combined_df

SLength  SWidth  PLength  Pwidth  class
30       4.8     3.1      1.6     0.2      0
15       5.7     4.4      1.5     0.4      0
104      6.5     3.0      5.8     2.2      2
6        4.6     3.4      1.4     0.3      0
91       6.1     3.0      4.6     1.4      1
..       ...     ...      ...     ...    ...
99       5.7     2.8      4.1     1.3      1
72       6.3     2.5      4.9     1.5      1
49       5.0     3.3      1.4     0.2      0
21       5.1     3.7      1.5     0.4      0
45       4.8     3.0      1.4     0.3      0

[142 rows x 5 columns]

In [11]:
class_labels=[]
distance_values=[]
for index,row in combined_df.iterrows():
    feature_values =row.values[:-1]#exclude class labels
    print(feature_values,end='\n')


[4.8 3.1 1.6 0.2]
[5.7 4.4 1.5 0.4]
[6.5 3.  5.8 2.2]
[4.6 3.4 1.4 0.3]
[6.1 3.  4.6 1.4]
[4.6 3.2 1.4 0.2]
[5.5 2.4 3.8 1.1]
[6.4 2.8 5.6 2.1]
[4.6 3.6 1.  0.2]
[7.7 2.6 6.9 2.3]
[5.  3.4 1.5 0.2]
[4.9 3.1 1.5 0.1]
[6.5 3.  5.2 2. ]
[4.4 3.2 1.3 0.2]
[5.4 3.4 1.5 0.4]
[4.8 3.  1.4 0.1]
[5.2 4.1 1.5 0.1]
[6.9 3.1 5.1 2.3]
[4.9 2.5 4.5 1.7]
[4.9 3.1 1.5 0.1]
[6.5 3.2 5.1 2. ]
[6.6 2.9 4.6 1.3]
[5.9 3.2 4.8 1.8]
[6.  2.2 5.  1.5]
[5.  2.  3.5 1. ]
[6.3 3.3 4.7 1.6]
[5.2 2.7 3.9 1.4]
[6.3 2.8 5.1 1.5]
[5.4 3.7 1.5 0.2]
[5.8 2.7 5.1 1.9]
[5.6 2.7 4.2 1.3]
[4.8 3.4 1.9 0.2]
[5.6 2.8 4.9 2. ]
[5.4 3.4 1.7 0.2]
[5.9 3.  4.2 1.5]
[5.7 2.9 4.2 1.3]
[6.  2.2 4.  1. ]
[6.  2.9 4.5 1.5]
[4.9 3.  1.4 0.2]
[6.3 2.7 4.9 1.8]
[4.9 3.1 1.5 0.1]
[5.4 3.9 1.3 0.4]
[5.1 3.8 1.9 0.4]
[6.4 2.7 5.3 1.9]
[5.6 2.9 3.6 1.3]
[5.8 2.7 4.1 1. ]
[6.7 3.1 4.7 1.5]
[5.5 4.2 1.4 0.2]
[5.4 3.  4.5 1.5]
[5.1 3.3 1.7 0.5]
[4.7 3.2 1.6 0.2]
[4.5 2.3 1.3 0.3]
[5.  2.3 3.3 1. ]
[5.1 3.5 1.4 0.3]
[7.1 3.  5.9 2.1]
[6.5 2.8 4

In [ ]:
import numpy as np
for index,row in X_test.iterrows():
    distance_values =[]
    test_set_vector=row.values
    #the next step is to compute the euclidean distance of the sample vector with each of the vectors present in the training set
    for indexx,roww in combined_df.iterrows():
        training_sample = roww.values[:-1]
        # we are using dot product
        #test_vector = [x1 x2 x3]  , traing sample =[y1 y2 y3]  -> dot product = [x1y1 x2y2 x3y3]
        #training_sample - test_vestor = [y1-x1 y2-x2 y3-x3]
        #dot producting itself will gives =[(y1-x1)**2,(y2-x2)**2,]

        euclidean_distance =np.dot(training_sample-test_set_vector,training_sample-test_set_vector)**0.5

        distance_values.append(euclidean_distance) 
        #after the completion of the inner loop, distances_values will store the euclidean distance
        # of the test_set_vector with all feature training sampls present in my training set.
        #Essentially "test_set_vector" will have 142 distance values (142,5)

    #temp_df=combined_df.copy()
    #creating new row to store distance 
    combined_df['distance'] = distance_values
    sorted_df = combined_df.sort_values(by='distance',ascending=True)
    top_K_near = sorted_df.head(5)#k=5

    class_label = top_K_near['class'].value_counts(ascending=False).index[0] 
    class_labels.append(class_label)
    #after 1st iteration,combined_df will have new column distance.we have to drop that inorder to perform the dot product in following iterations,because otherwise shape will change
    combined_df =combined_df.drop(columns=['distance'])



In [13]:
class_labels_series_obj =pd.Series(class_labels)

In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test,class_labels_series_obj))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



From library

In [16]:
from sklearn.neighbors import KNeighborsClassifier
knn_object = KNeighborsClassifier(n_neighbors=5)

In [17]:
knn_object.fit(X_train,y_train)
class_labels= knn_object.predict(X_test)
class_labels

array([1, 0, 2, 2, 1, 0, 1, 2], dtype=int64)

In [18]:
print(classification_report(class_labels,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         3

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8



In [ ]:
knn_obj2 =KNeighborsClassifier(n_neighbors=10,p=1) #p 

In [20]:
knn_obj2.fit(X_train,y_train)
class_labels= knn_obj2.predict(X_test)

In [21]:
print(classification_report(class_labels,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       0.67      1.00      0.80         2
           2       1.00      0.75      0.86         4

    accuracy                           0.88         8
   macro avg       0.89      0.92      0.89         8
weighted avg       0.92      0.88      0.88         8

